name: Cypress Run in Docker

on:
  workflow_dispatch:

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Open repositoriy
        uses: actions/checkout@v3

      - name: Run Cypress tests in Docker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/e2e \
            -w /e2e \
            cypress/browsers:node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1/images/sha256-c2f9b80afa112a99157b3f4bec793c7651bb9bdc292eb2a792e1ed4512763304?context=explore
            npx cypress run